<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <OutputPath>bin\$(Configuration)\Mods</OutputPath>
        <Nullable>enable</Nullable>
        <Version>1.0.0</Version>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>
        <RootNamespace>QueueAPI</RootNamespace>

        <Title>Queue API</Title>
        <Description>Provides an API for other mods to interact with the player join queue.</Description>
        <PackageId>Cecer.VinageStory.QueueAPI</PackageId>
        <RepositoryUrl>https://github.com/Cecer/VS-QueueAPI/</RepositoryUrl>
        <PackageProjectUrl>https://mods.vintagestory.at/queueapi</PackageProjectUrl>
        <EmbedAllSources>true</EmbedAllSources>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="VintagestoryAPI">
            <HintPath>$(VINTAGE_STORY)/VintagestoryAPI.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="VintagestoryLib">
            <HintPath>$(VINTAGE_STORY)/VintagestoryLib.dll</HintPath>
            <Private>False</Private>
        </Reference>
        
        <Reference Include="0Harmony">
            <HintPath>$(VINTAGE_STORY)/Lib/0Harmony.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Mono.Cecil">
            <HintPath>$(VINTAGE_STORY)\Lib\Mono.Cecil.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>

</Project>
